# Generated by Django 2.0.5 on 2018-06-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0014_auto_20180523_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='tMyServerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerName', models.CharField(max_length=40, null=True, verbose_name='Server Name')),
            ],
            options={
                'verbose_name': 'MyServerinfo',
                'verbose_name_plural': 'MyServerinfo',
            },
        ),
        migrations.AlterField(
            model_name='tdevice',
            name='Remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Remark'),
        ),
        migrations.AddField(
            model_name='tmyserverinfo',
            name='DeviceSeq',
            field=models.ForeignKey(blank=True, db_column='CDeviceSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDevice', verbose_name='Child Device'),
        ),
        migrations.AlterUniqueTogether(
            name='tmyserverinfo',
            unique_together={('ServerName', 'DeviceSeq')},
        ),
    ]
