# Generated by Django 2.0.5 on 2018-06-12 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0015_auto_20180612_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmyserverinfo',
            name='DeviceSeq',
            field=models.ForeignKey(blank=True, db_column='DeviceSeq', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='IOTApp.tDevice', verbose_name='Device Info'),
        ),
    ]
