# Generated by Django 2.0.5 on 2018-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IOTApp', '0016_auto_20180612_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmyserverinfo',
            name='DatastoreIPaddress',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Datastore IP address'),
        ),
        migrations.AddField(
            model_name='tmyserverinfo',
            name='IPaddress',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='My IP address'),
        ),
    ]
